#133 helm chart update

diff --git a/deploy/helm/charts/postgres/templates/statefulset.yaml b/deploy/helm/charts/postgres/templates/statefulset.yaml
--- a/deploy/helm/charts/postgres/templates/statefulset.yaml
+++ b/deploy/helm/charts/postgres/templates/statefulset.yaml
@@ -30,6 +30,7 @@ spec:
               ordinal=${BASH_REMATCH[1]}
               if [[ $ordinal -eq 0 ]]; then
                 cp /mnt/replica-config/primary.conf /etc/postgresql/postgresql.conf
+                cp /mnt/replica-config/pg_hba.conf /etc/postgresql/pg_hba.conf
                 cp /mnt/replica-config/primary.sql /docker-entrypoint-initdb.d/init.sql
               else
                 cp /mnt/replica-config/replica.conf /etc/postgresql/postgresql.conf
@@ -54,10 +55,17 @@ spec:
             - bash
             - -c
             - |
-              if [[ `hostname` =~ -([0-9]+)$ && ${BASH_REMATCH[1]} -ne 0 ]]; then
-                bash /etc/postgresql/secondary.sh
+              hostname=$(hostname)
+              if [[ "$hostname" =~ -([0-9]+)$ ]]; then
+                ordinal="${BASH_REMATCH[1]}"
+                if [[ "$ordinal" -ne 0 ]]; then
+                  bash /etc/postgresql/secondary.sh
+                else
+                  exec docker-entrypoint.sh postgres
+                fi
               else
-                exec docker-entrypoint.sh postgres
+                echo "Failed to extract ordinal from hostname"
+                exit 1
               fi
           env:
             # Using Secrets
@@ -92,9 +100,6 @@ spec:
               mountPath: /var/lib/postgresql/data
             - name: postgres-conf # initContainer 가 ConfigMap 에서 복사한 파일
               mountPath: /etc/postgresql
-            - name: postgres-conf
-              mountPath: /var/lib/postgresql/data/pg_hba.conf
-              subPath: pg_hba.conf
             - name: initdb-d  # initContainer 가 ConfigMap 에서 복사한 시작 파일
               mountPath: /docker-entrypoint-initdb.d
             - name: dump-backup
