workflows update

diff --git a/.github/workflows/helm_dev.yml b/.github/workflows/helm_dev.yml
--- a/.github/workflows/helm_dev.yml
+++ b/.github/workflows/helm_dev.yml
@@ -47,8 +47,21 @@ jobs:
             kubectl apply -f ../kubectl/class-roles
             
             if [ -e "./values-dev-custom.yaml" ]; then
+              echo "Custom values-dev-custom.yaml found. Running dev-deploy.sh..."
               sh dev-deploy.sh
+            
+              if [ $? -ne 0 ]; then
+                echo "dev-deploy.sh failed. Falling back to inline Helm deployment."
+                run_inline_helm_deploy=true
+              else
+                run_inline_helm_deploy=false
+              fi
             else
+              echo "values-dev-custom.yaml not found. Proceeding with inline Helm deployment."
+              run_inline_helm_deploy=true
+            fi
+            
+            if [ "$run_inline_helm_deploy" = true ]; then
               if ! helm repo list | grep -q 'nfs-subdir-external-provisioner'; then
                 helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
               fi
