workflows update

diff --git a/.github/workflows/helm_prod.yml b/.github/workflows/helm_prod.yml
--- a/.github/workflows/helm_prod.yml
+++ b/.github/workflows/helm_prod.yml
@@ -46,8 +46,21 @@ jobs:
             kubectl apply -f ../kubectl/class-roles
             
             if [ -e "./values-prod-custom.yaml" ]; then
+              echo "Custom values-prod-custom.yaml found. Running prod-deploy.sh..."
               sh prod-deploy.sh
+            
+              if [ $? -ne 0 ]; then
+                echo "prod-deploy.sh failed. Falling back to inline Helm deployment."
+                run_inline_helm_deploy=true
+              else
+                run_inline_helm_deploy=false
+              fi
             else
+              echo "values-prod-custom.yaml not found. Proceeding with inline Helm deployment."
+              run_inline_helm_deploy=true
+            fi
+            
+            if [ "$run_inline_helm_deploy" = true ]; then
               if ! helm repo list | grep -q 'nfs-subdir-external-provisioner'; then
                 helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
               fi
@@ -58,7 +71,7 @@ jobs:
                      --set nfs.server=${{ secrets.CICD_HOST }} \
                      --set nfs.path=/mnt/nfs-subdir-external-provisioner
               fi
-                 
+            
               helm upgrade ${{ secrets.DATABASE_USER }} . -f ./values-prod.yaml \
                 --install -n ibs-prod --create-namespace --history-max 5 --wait --timeout 10m \
                 --set global.dbPassword=${{ secrets.DATABASE_PASS }} \
